import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContentGrid from "@/components/content-grid";
import Header from "@/components/header";
import Footer from "@/components/footer";

const interSans = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interSans.className} antialiased bg-[#e2e4eb]`}>
        <ContentGrid className={"min-h-dvh grid-rows-[auto_1fr_auto] gap-4"}>
          <Header />
          <main>{children}</main>
          <Footer />
        </ContentGrid>
      </body>
    </html>
  );
}
